version: 0.1.6-{build}

shallow_clone: true

environment:
  LUAROCKS_VER: 2.4.1
  LUA_VER: 5.1.4
  CURRENT_BRANCH: develop # Branch for shell and framework

platform:
  - x86
  - x64

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

install:
- git clone https://github.com/lidesdk/appveyor_lua.git .appveyor
# Make compiler command line tools available
- call .appveyor\set_compiler_env.bat
# Setup Lua development/build environment
- call .appveyor\install.bat

before_build:
  - echo "Installing external deps"
  - luarocks install luafilesystem

build_script:

  # Create lide install directory and go to it (C:\lide):
  - mkdir C:\lide

  # Clone git repository and submodules:
  - git clone https://github.com/lidesdk/shell.git --recursive C:\lide\shell && cd C:\lide\shell && git pull origin %CURRENT_BRANCH%  && git checkout %CURRENT_BRANCH% && cd C:\lide\shell\libraries\lide && git checkout %CURRENT_BRANCH%

  # Create environment variable named LIDE_PATH:
  - set LIDE_PATH=C:\lide\shell
  - set PATH=%LIDE_PATH%;

test_script:
- cd c:\projects\bit32
- lide install bit32 5.2.2
  
  # Simulate lide's package.path and package.cpath on default lua5.1 interpreter
- call %LIDE_PATH%\bin\windows\x86\lua5.1.exe %LIDE_PATH%\bin\lide51.lua tests\test.lua